on: [push]

jobs:
  build_and_upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: sudo apt install -y libhts-dev libboost-random-dev

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build package
        run: |
          poetry install
          poetry build

      # For the sake of simplicity, we'll name the tag and the release with
      # the first 8 chars of the commit SHA:
      - name: Get short SHA
        id: short_sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Release
        uses: softprops/action-gh-release@v1 
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          name: canary-${{ steps.short_sha.outputs.sha8 }}
          tag_name: canary-${{ steps.short_sha.outputs.sha8 }}
          prerelease: true
          files: |
            dist/*